alias: 15 mins post Sundown - Livingroom Lights on
description: ""
trigger:
  - platform: sun
    event: sunset
    offset: "15"
condition:
  - condition: state
    entity_id: light.livingroom_couch
    state: "off"
action:
  - service: scene.turn_on
    target:
      entity_id: scene.livingroom_off
    metadata: {}
mode: single
